### PR TITLE
Fixing CI

### PR DESCRIPTION
**Pull request by facastagnini**
Some simple updates to bring CI back to life.
There is a lot of red, I will fix that in a different PR, if this change gets merged :P

### CODE REVIEW

**Comment by facastagnini** [comment]
No one with write access?

**Comment by phoolish** [comment]
I will try and take a look at this today.  May have to wait until tomorrow.

**Comment by facastagnini** [comment]
Thanks @phoolish !

**Comment by phoolish** [comment]
Looks good.  I was planning on updating CI this summer, but any assistance is appreciated.

**Comment by facastagnini** [comment]
glad to help man

**Pull request merged**
